export Header from './HeaderFooter/Header'
export Footer from './HeaderFooter/Footer'
export SecondaryHeader from './HeaderFooter/SecondaryHeader'

export PrivacyPolicy from './LegalComponents/PrivacyPolicy'
export Terms from './LegalComponents/Terms'

// export CategoryList from './SubComponents/CategoryList'
// export EquipmentList from './SubComponents/EquipmentList'
// export IngredientList from './SubComponents/IngredientList'
// export LearningPathList from './SubComponents/LearningPathList'
export Recipe from './Recipe/Recipe'
// export RecipeComponentDetailed from './SubComponents/RecipeComponentDetailed'
// export RecipeFromAPI from './SubComponents/RecipeFromAPI'
// export SkillsLearntList from './SubComponents/SkillsLearntList'
// export StepList from './SubComponents/StepList'
// export TagList from './SubComponents/TagList'

// export RecipeComponent from './SubComponents/RecipeComponent'
export RecipeList from './RecipeList/RecipeList'
// export RecipeListFromAPI from './SubComponents/RecipeListFromAPI'
// export RecipeOverview from './SubComponents/RecipeOverview'
